server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            maxAge: 3600
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/public/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**


        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: consultation-service
          uri: lb://CONSULTATION-SERVICE
          predicates:
            - Path=/consultation/**
          filters:
            - AuthenticationFilter

        - id: consultation-service
          uri: lb://CONSULTATION-SERVICE
          predicates:
            - Path=/plan/**

  application:
    name: UNLEASH-GATEWAY

