server:
  port: 8080
spring:
  servlet:
    multipart.enabled: true
    multipart.max-file-size: 20MB
    multipart.max-request-size: 20MB
  dataSource:
    url: jdbc:mysql://localhost:3306/unleash_userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      com.unleash: DEBUG
      org.hibernate: TRACE
      org.springframework.security: TRACE
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
